name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: tobangado69
          gif_out_path: ./output/github-contribution-grid-snake.gif
          svg_out_path: ./output/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: ./output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
