name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Snake
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: tobangado69
          gif_out_path: ./output/github-contribution-grid-snake.gif
          svg_out_path: ./output/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generate contribution snake'
          add: 'output/github-contribution-grid-snake.*'
